[package]
name = "domain-model"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quote = "1.0.37"
rust_decimal = "1.36.0"
rust_decimal_macros = "1.36.0"
syn = "2.0.79"
